server:
  port: 1005
spring:
  application:
    name: microservice-read-properties
  cloud:
    config:
      discovery:  #配置文件服务地址
        service-id: system-config-server
        enabled: true
        profile: dev            # profile对应config server所获取的配置文件中的{profile}
        label: dev           # 指定Git仓库的分支，对应config server所获取的配置文件的{label}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka
    registry-fetch-interval-seconds: 10

name: liupeiiqng