server:
  port: 1025
spring:
  application:
    name: microservice-elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch #默认即为elasticsearch
      cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:   http://eureka-primary:8011/eureka/