auth-server: http://localhost:1022
server:
  port: 1023
  context-path: /client1
spring:
  application:
    name: microservice-sso-client1
security:
  oauth2:
    client:
      client-id: client_1
      client-secret: secret
      user-authorization-uri: ${auth-server}/oauth/authorize   #请求认证的服务器地址  是授权用户被重定向的目标URL
      access-token-uri: ${auth-server}/oauth/token  #请求令牌的地址  是获取访问令牌的URL
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key  #解析jwt令牌所需要密钥的地址
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/  #客户端与服务端交互的zone的地址  zone类似于机房 eureka放在机房里面(zong)