server:
  port: 1014
spring:
  application:
    name: microservice-async
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://eureka-primary:8011/eureka/
