auth-server: http://localhost:1022
server:
  context-path: /client2
  port: 1024
security:
  oauth2:
    client:
      client-id: wuqianqian2
      client-secret: wuqianqiansecrect2
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/  #客户端与服务端交互的zone的地址  zone类似于机房 eureka放在机房里面(zong)