server:
  port: 1014
spring:
  application:
    name: microservice-aop
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/  #客户端与服务端交互的zone的地址  zone类似于机房 eureka放在机房里面(zong)