server:
  port: 1004
spring:
  application:
    name:  microservice-config-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: system-config-server
        profile: dev            # profile对应config server所获取的配置文件中的{profile}
        label: dev    
